$jsonPath = "data\articles.json"
$content = Get-Content -Raw -Path $jsonPath -Encoding UTF8
$data = $content | ConvertFrom-Json

$data[0].articles[0].text = "Article 1. Name and territory of the Union.— `n(1) India, that is Bharat, shall be a Union of States. `n1 [(2) The States and the territories thereof shall be as specified in the First Schedule.] (3) The territory of India shall comprise—`n(a) the territories of the States; `n2[(b) the Union territories specified in the First Schedule; and] `n(c) such other territories as may be acquired.`nAmendment: `nClause (2) was substituted by the Constitution (Seventh Amendment) Act, 1956, s. 2 (w.e.f. 1-11-1956).`nSub-clause (b) of Clause (3) was substituted by the Constitution (Seventh Amendment) Act, 1956, s. 2 (w.e.f. 1-11-1956)."

$data[0].articles[1].text = "Article 2. Admission or establishment of new States.— Parliament may by law admit into the Union, or establish, new States on such terms and conditions as it thinks fit."

$data[0].articles[2].text = "Article 2A. [Sikkim to be associated with the Union.] — Omitted by the Constitution (Thirty-sixth Amendment) Act, 1975, s. 5 (w.e.f. 26-4-1975).`nAmendment: `nThis article was originally inserted by the Constitution (Thirty-fifth Amendment) Act, 1974, s. 2 (w.e.f. 1-3-1975), which was subsequently omitted by the 36th Amendment."

$data[0].articles[3].text = "Article 3. Formation of new States and alteration of areas, boundaries or names of existing States.— `nParliament may by law— `n(a) form a new State by separation of territory from any State or by uniting two or more States or parts of States or by uniting any territory to a part of any State; `n(b) increase the area of any State; `n(c) diminish the area of any State; `n(d) alter the boundaries of any State; `n(e) alter the name of any State: `n1[Provided that no Bill for the purpose shall be introduced in either House of Parliament except on the recommendation of the President and unless, where the proposal contained in the Bill affects the area, boundaries or name of any of the States2***, the Bill has been referred by the President to the Legislature of that State for expressing its views thereon within such period as may be specified in the reference or within such further period as the President may allow and the period so specified or allowed has expired.] `n3[Explanation I.—In this article, in clauses (a) to (e), “State” includes a Union territory, but in the proviso, “State” does not include a Union territory. Explanation II.—The power conferred on Parliament by clause (a) includes the power to form a new State or Union territory by uniting a part of any State or Union territory to any other State or Union territory.]`nAmendment: `nSubs. by the Constitution (Fifth Amendment) Act, 1955, s. 2, for the proviso (w.e.f. 24-12-1955). `nThe words and letters `"specified in Part A or Part B of the First Schedule`" omitted by the Constitution (Seventh Amendment) Act, 1956, s. 29 and Sch. (w.e.f. 1-11-1956). `nIns. by the Constitution (Eighteenth Amendment) Act, 1966, s. 2 (w.e.f. 27-8-1966)."

$data[0].articles[4].text = "Article 4. Laws made under articles 2 and 3 to provide for the amendment of the First and the Fourth Schedules and supplemental, incidental and consequential matters.— `n(1) Any law referred to in article 2 or article 3 shall contain such provisions for the amendment of the First Schedule and the Fourth Schedule as may be necessary to give effect to the provisions of the law and may also contain such supplemental, incidental and consequential provisions (including provisions as to representation in Parliament and in the Legislature or Legislatures of the State or States affected by such law) as Parliament may deem necessary. `n(2) No such law as aforesaid shall be deemed to be an amendment of this Constitution for the purposes of article 368."

$jsonString = $data | ConvertTo-Json -Depth 10
[System.IO.File]::WriteAllText((Get-Item $jsonPath).FullName, $jsonString, [System.Text.Encoding]::UTF8)

Write-Host "Updated JSON file via PowerShell successfully."
